version: '2'
services:
  rabbit:
    image: rabbitmq:3.6.10-management-alpine
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "4369:4369"
      - "15672:15672"

  worker:
    build: .
    image: sjbitcode/panchang
    container_name: worker
    command: celery -A panchang.main worker -l info --beat
    volumes:
      - .:/worker
    depends_on:
      - rabbit
    env_file:
      - ./deploy/env/dev/worker.env
